### ISSUE TITLE
signature discussion

### ISSUE THREAD

**Issue by krawaller** [staltz/callbag-sample#1]
I'm wondering if `pullable => listenable => newSource` wouldn't be a more natural signature than `listenable => pullable => newSource`. Granted I haven't really thought this through, but it feels more intuitive to want to use this while operating on the `listenable`, and not the `pullable`. 

For example, in my little callbag test app I did something like this:

```
const submitActions = pipe(
  merge(hitEnter, fromEvent(ui.submit, "click")),
  sample(latest(typeStream)), // reverse signature!
  filter(s => s.length),
  map(v => ({type:'SET', val: v}))
);
```

In other words, I begin with a listenable stream of submit events, then by using `sample` I wanted to "map" those to the latest value from `typeStream`, using the pullable source `latest(typeStream)` (using home-brewed `latest` helper). But for this to work, the `pullable` needs to be the operator argument instead of `listenable`.

Of course I could just have written it targetting the current signature: 

```
const submitActions = pipe(
  latest(typeStream)
  sample(merge(hitEnter, fromEvent(ui.submit, "click"))),
  filter(s => s.length),
  map(v => ({type:'SET', val: v}))
);
```

...but it didn't feel as intuitive. I'm guessing it boils down to whether `sample` is short for `sampleFrom` or `sampleWhen`.

Anyhow, mostly just thinking out loud. Probably there is prior art saying I'm simply wrong? :)

**Comment by staltz** [comment]
I think you're absolutely right! Actually I thought I had done the way you suggest, but I just got messed up with the signature. For some reason I though `listenable => pullable => newSource` would mean "we start with a listenable and pass it through a pullable" but it's the other way around.

So, yes, a sample should feel like a map, and it should be `pullable => listenableIn => listenableOut`

I should code this and release 2.0
